[build]
build-std = true                              # do not build the std library. has precedence over xargo
xargo = true                                   # enable the use of xargo by default
zig = true                                    # do not use zig cc for the builds
pre-build = ["./install-rust-src"]


[target.x86_64-unknown-linux-musl]
pre-build = ["./install-rust-src"]
[target.x86_64-unknown-linux-gnu]
pre-build = ["./install-rust-src"]
[target.arm-unknown-linux-gnueabi]
pre-build = ["./install-rust-src"]
[target.arm-unknown-linux-gnueabihf]
pre-build = ["./install-rust-src"]
[target.aarch64-unknown-linux-gnu]
pre-build = ["./install-rust-src"]
[target.aarch64-unknown-linux-musl]
pre-build = ["./install-rust-src"]
[target.i686-unknown-linux-gnu]
pre-build = ["./install-rust-src"]
[target.i686-unknown-linux-musl]
pre-build = ["./install-rust-src"]
[target.arm-unknown-linux-musleabi]
pre-build = ["./install-rust-src"]
[target.arm-unknown-linux-musleabihf]
pre-build = ["./install-rust-src"]
[target.armv5te-unknown-linux-gnueabi]
pre-build = ["./install-rust-src"]
[target.armv5te-unknown-linux-musleabi]
pre-build = ["./install-rust-src"]
[target.armv7-unknown-linux-musleabi]
pre-build = ["./install-rust-src"]
[target.armv7-unknown-linux-musleabihf]
pre-build = ["./install-rust-src"]
[target.armv7-unknown-linux-gnueabihf]
pre-build = ["./install-rust-src"]
[target.armv7-unknown-linux-gnueabi]
pre-build = ["./install-rust-src"]